- hosts: all
  tasks:
  - name: Execute a command using the shell module
    become: true
    become_user: root
    shell: bash <(curl -Ss https://my-netdata.io/kickstart.sh)
           sudo firewall-cmd --permanent --zone=public --add-port=19999/tcp
